name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Setup (Common)
      run: |
        mkdir build
        python -m pip install setuptools wheel
    - name: Setup (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl
        echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV
        echo "VIRTUAL_ENV=/Users/runner/hostedtoolcache/Python/${{ matrix.python-version }}" >> $GITHUB_ENV
    - name: Setup (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install openssl
        echo "VIRTUAL_ENV=C:\\hostedtoolcache\\windows\\Python\\${{ matrix.python-version }}" >> $GITHUB_ENV
    - name: Configure
      working-directory: build
      run: |
        cmake ..
    - name: Build
      working-directory: build
      run: |
        cmake --build . && cmake --build . --target wheel
    - name: Wheel
      working-directory: build
      run: |
        cmake --build . --target wheel
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pyzswagcl-wheel
        path: build/pyzswagcl*.whl
